name: Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: android-diff
        uses: blendthink/android-diff-action@dev

      - uses: peter-evans/find-comment@v1
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Android Diff

      - uses: peter-evans/create-or-update-comment@v1
        with:
          body: |
            ## Android Diff

            ${{ steps.android-diff.outputs.diff }}
          edit-mode: replace
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}